//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NullaGroupHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModImage
    {
        public int Id { get; set; }
        public int ModId { get; set; }
        public string Uploader { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string Information { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ModName ModName { get; set; }
    }
}
