//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NullaGroupHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionInfo
    {
        public int Id { get; set; }
        public int ModId { get; set; }
        public string GameVersion { get; set; }
        public string VersionType { get; set; }
        public string Version { get; set; }
        public string PrepositionModName { get; set; }
        public string PrepositionType { get; set; }
        public string PrepositionVersion { get; set; }
    
        public virtual ModName ModName { get; set; }
    }
}
